### ISSUE TITLE
Do document extensions work with the personal edition?

### ISSUE THREAD

**Issue by rmarkar** [stefanwalther/qvAutoRefresh#1]
Do document extensions work with the personal edition?
I have installed the auto refresh document extension successfully and trying to view data in webview.. but the same does not appear to refresh at regular intervals.. Can anyone plz suggest...

**Comment by stefanwalther** [comment]
@rmarkar: Did you create the variable `vAutoRefresh_NextRefresh` ?

Regards
Stefan

**Comment by stefanwalther** [comment]
Didn't receive an answer, so close it.
