### ISSUE TITLE
What kind of webclient can qvAutoRefresh work?

### ISSUE THREAD

**Issue by worldalan** [stefanwalther/qvAutoRefresh#2]
Hi Stefan,
It seems the autorefresh can't work at 'Full Browser Version' and 'Small Device Version', but works at 'Internet Explorer Plugin'. Furthermore, if there're more than 3 sessions opened for the scheduled document, the autorefresh doesn't work neither.

**Comment by stefanwalther** [comment]
qvAutoRefresh is an extension and cannot work in the Internet Explorer Plugin.
