### ISSUE TITLE
AutoRefresh - on-demand?

### ISSUE THREAD

**Issue by GeoMarketDallas** [stefanwalther/qvAutoRefresh#3]
Hello,
Can your extension for a timed refresh be activated by a button action or variable trigger?

I need to refresh the browser (QV app) on-demand and not on a timed schedule.

Thanks,
Mike Strube
Dallas

**Comment by worldalan** [comment]
The AutoRefresh is triggered by the variable vAutoRefresh_NextRefresh, set variable "vAutoRefresh_NextRefresh"=now() in the button object should work.

**Comment by GeoMarketDallas** [comment]
Thank you. I will give that a try.

Also, I really enjoy your site.  We create advanced extension objects for our QV OEM products. I will see what we can share.  Plus, we are a long-time ESRI partner. So we have an advanced QV-ESRI connector.  We are about finished w/ a Sense to ESRI connector.

Stay in touch.

Mike
